name: "coffeenotfound.github.io"
permalink: "/:slug/"
baseurl: "/"
url: "coffeenotfound.github.io"
encoding: "utf-8"

author: "Jan Katzer"
sitedescription: "[ no description here... ]"
sitetags: ["Jekyll", "HTML", "CSS", "Java", "JavaScript", "JS", "coding", "programming", "coffeenotfound"]

#twitter:
#  username: twitterhandle

#facebook:
#  app_id: 1234
#  publisher: 1234
#  admins: 1234

#gems: ["jekyll-paginate", "jemoji", "jekyll-compass", "jekyll-lunr-js-search"]

paginate: 5
paginate_path: "blog/:num"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: "/blog/:slug/"
      layout: "post"
      author: "Jan Katzer"
      excerpt_separator: "<!--more-->"
      #og-title: "{{ page.title }}"
      #og-image: "favicon.ico"
      #og-description: "{{ page.excerpt }}"

#sass:
#  style: compressed

keep_files: [.git, README.md]
exclude: [.gitignore, Gemfile, Gemfile.lock, README.md, ISSUES.txt, "$build-site.sh", "$publish-site.sh"]