title: "My Awesome Blog"

description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""

permalink: '/:slug/'
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/blog/:slug/"

markdown: kramdown
highlighter: rouge

excerpt_separator: "<!-- endexcerpt -->"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

keep_files: [.git, README.md]
