title: "My Awesome Blog"

description: >
  My personal blog/random stuff website. Blog posts optional.
baseurl: ""
permalink: '/:slug/'

collections:
  projectpages:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/blog/:slug/"
      author: "Jan Katzer"
      author-url: "/about/"
  -
    scope:
      path: ""
      type: "projectpages"
    values:
      permalink: "/projects/:slug/"

markdown: kramdown
highlighter: rouge

excerpt_separator: "<!-- endexcerpt -->"

exclude: [Gemfile, Gemfile.lock, README.md]
keep_files: [.git, .nojekyll, README.md, CNAME]
